services:
  - type: web
    name: fake-news-detector
    env: python
    plan: free
    buildCommand: git lfs pull && pip install -r requirements.txt
    pythonVersion: 3.11.11
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: RENDER
        value: true
    healthCheckPath: /api/health
    autoDeploy: true
